runtime: nodejs10
env: standard

handlers:
  - url: /assets
    static_dir: static/assets/

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

manual_scaling:
  instances: 5 
